---
name: OpenWisp2 Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build: Python==3.7
  runs-on: ubuntu-20.04

  strategy:
    fail-fast: false

  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install python dependencies
      run: |
        pip install -U "pip==20.2.4" wheel
        pip install -U -r requirements.txt
        pip install pylinkvalidator

    - name: QA checks
      run: |
        ./run-qa-checks
